### ISSUE TITLE
 passing to targetting state remains

### ISSUE THREAD

**Issue by therkut** [matthewmiglio/Py-TwitterBot#12]
Hello,
I want to use the application but it seems like it is not working, can you please check it again?

**Comment by therkut** [comment]
[Previous line repeated 991 more times]
RecursionError: maximum recursion depth exceeded

**Comment by therkut** [comment]
return click_follower_button_of_profile_page(driver, logger, attempt=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 991 more times]
RecursionError: maximum recursion depth exceeded

**Comment by matthewmiglio** [comment]
I completely refreshed the repository if you'd like to try it out now

**Comment by therkut** [comment]
Thank you for your correction, I will definitely let you know the test result.
